### ISSUE TITLE
feat(trace): filter traces by span name in addition to service name

### ISSUE THREAD

**Issue by ymtdzzz** [ymtdzzz/otel-tui#118]

**Comment by ymtdzzz** [comment]
> Right now, you can refine the trace list by service name. I think it could be helpful to have another expression, maybe span name. This can help for instrumentation that make a ton of spans and you can't really know which are which. It may be helpful in the overview to show the root span name for the same reason.

https://github.com/ymtdzzz/otel-tui/issues/130#issue-2464943004

**Comment by ymtdzzz** [comment]
I'm currently working on this issue

**Comment by codefromthecrypt** [comment]
thanks for all the support! see you in a few days
