### ISSUE TITLE
format specifier miss on span details page

### ISSUE THREAD

**Issue by codefromthecrypt** [ymtdzzz/otel-tui#120]
I think we need a %v somewhere because the attribute values can be non-string

<img width="409" alt="Screenshot 2024-08-01 at 5 27 03 PM" src="https://github.com/user-attachments/assets/03b0e090-18d0-42d6-9b38-6910d663bf88">

**Comment by ymtdzzz** [comment]
This issue is fixed on the release https://github.com/ymtdzzz/otel-tui/releases/tag/v0.2.2 :D
Thanks for reporting and please let me know if you find any other issues!
