### ISSUE TITLE
zipkin json v2 endpoint

### ISSUE THREAD

**Issue by codefromthecrypt** [ymtdzzz/otel-tui#125]
In my free time, I still work on zipkin, and we have a ton of examples. While I like our server, for the type of work I do I prefer a text terminal. If otel-tui accepted the POST endpoint of zipkin spans (port 9411), I could look at the data pretty easily. Also people who haven't migrated to OTLP could use it, too.

Almost all users only use v2 json endpoint, so if you are interested you don't need the same level of sophistication as the collector

https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/23de1761434a8d069362cd233cbbbc77725def19/receiver/zipkinreceiver
https://github.com/openzipkin/brave-example
https://github.com/openzipkin/zipkin-api/blob/master/zipkin2-api.yaml#L60

**Comment by ymtdzzz** [comment]
Thanks for your interesting suggestion! Support for multiple formats, including zipkin, makes otel-tui more convenient for developers using distributed tracing.
otel-tui is just an exporter, so I think it might be possible to combine it with receivers like zipkinreceiver. I'll give it a try this weekend :)

**Comment by ymtdzzz** [comment]
IMO, it's enough to add zipkinreceiver to `go.mod` and call its `Factory()` with some yaml configurations just like: https://github.com/ymtdzzz/otel-tui/pull/126/files

yaml configurations in `main.go` looks like:

```diff
	rootCmd := &cobra.Command{
		Use:          params.BuildInfo.Command,
		Version:      params.BuildInfo.Version,
		SilenceUsage: true,
		RunE: func(cmd *cobra.Command, args []string) error {
			configContents := `yaml:
receivers:
  otlp:
    protocols:
      http:
        endpoint: ` + hostFlag + `:` + strconv.Itoa(httpPortFlag) + `
      grpc:
        endpoint: ` + hostFlag + `:` + strconv.Itoa(grpcPortFlag) + `

processors:

exporters:
  tui:

service:
  pipelines:
    traces:
-      receivers: [otlp]
+      receivers: [otlp, zipkin]
      processors: []
      exporters: [tui]
    logs:
      receivers: [otlp]
      processors: []
      exporters: [tui]
    metrics:
      receivers: [otlp]
      processors: []
      exporters: [tui]
`
```

**Comment by ymtdzzz** [comment]
@codefromthecrypt, I've created a PR to support zipkin: https://github.com/ymtdzzz/otel-tui/pull/127
Does it look like what you imagine?

**Comment by ymtdzzz** [comment]
From [v0.3.0](https://github.com/ymtdzzz/otel-tui/releases/tag/v0.3.0), the zipkin receiver (on the port `9411`) has been supported!
Please create an issue or reopen this if any problems :)

**Comment by codefromthecrypt** [comment]
looks beautiful. thanks @ymtdzzz!
