### ISSUE TITLE
refine trace list by span name

### ISSUE THREAD

**Issue by codefromthecrypt** [ymtdzzz/otel-tui#130]
Right now, you can refine the trace list by service name. I think it could be helpful to have another expression, maybe span name. This can help for instrumentation that make a ton of spans and you can't really know which are which. It may be helpful in the overview to show the root span name for the same reason.

**Comment by ymtdzzz** [comment]
Thanks but this issue seems to be duplicated of #118 .
However,

> It may be helpful in the overview to show the root span name for the same reason.

this sounds good so I made a new issue about it: #134 :)

**Comment by ymtdzzz** [comment]
duplicate: #118
