### ISSUE TITLE
resize trace detail pane

### ISSUE THREAD

**Issue by codefromthecrypt** [ymtdzzz/otel-tui#131]
Right now, we can use `Ctrl+L: Widen side col | Ctrl+H: Narrow side col` for the trace timelines pane. I would like to do the same when I select the details (d).

**Comment by ymtdzzz** [comment]
This makes sense. It would be easier than #38 to solve the problem of displaying the long attribute values, although there are limitations.

**Comment by ymtdzzz** [comment]
current progress:

![image](https://github.com/user-attachments/assets/c8ba4da5-63b6-47f4-8344-1f310e9edd3d)

![image](https://github.com/user-attachments/assets/ccd7f4a0-2c47-4f1a-9ff6-94a5ae853127)

**Comment by ymtdzzz** [comment]
@codefromthecrypt 
With the changes in #139, we can now resize the details pane by pressing `Ctrl+H` and `Ctrl+L`.
(Note that this is only enabled when the details pane is focused)

**Comment by codefromthecrypt** [comment]
thanks so much!
