### ISSUE TITLE
Mark the span whose status is ERROR

### ISSUE THREAD

**Issue by ymtdzzz** [ymtdzzz/otel-tui#137]
In OpenTelemetry specification, a span has status.
cf. https://opentelemetry.io/docs/concepts/signals/traces/#span-status

It would be helpful to mark the span that has an error status.

**Comment by ymtdzzz** [comment]
![image](https://github.com/user-attachments/assets/95e4fe14-a828-477c-8098-3394e200b607)

**Comment by codefromthecrypt** [comment]
so [!] means error right?

**Comment by ymtdzzz** [comment]
yes but maybe there is better way to mark it 😅

**Comment by codefromthecrypt** [comment]
Maybe X or ! are both good choices for normal ascii

**Comment by ymtdzzz** [comment]
If any points of improvement, new issue can be made.
