### ISSUE TITLE
only show logs when there are logs

### ISSUE THREAD

**Issue by codefromthecrypt** [ymtdzzz/otel-tui#143]
I would like to not have to scroll when there are no logs. In this image you can see the space used for logs when there aren't any. If logs could be collapsed I can see everything at once!

<img width="1614" alt="Screenshot 2024-08-21 at 2 14 45 PM" src="https://github.com/user-attachments/assets/694e40de-0ad4-41c9-8d8c-6136af36e348">

**Comment by ymtdzzz** [comment]
I agree, It would be better to make Logs pane collapsible and collapsed by default whether the trace has logs or not.

**Comment by ymtdzzz** [comment]
@codefromthecrypt
Now, the logs pane has become collapsible and collapsed by default.

**Comment by codefromthecrypt** [comment]
thanks a lot!
