### ISSUE TITLE
Add root span latency to the summary screen

### ISSUE THREAD

**Issue by codefromthecrypt** [ymtdzzz/otel-tui#154]
Especially for traces that are single span, it is more helpful to see root span latency than the trace ID in the traces list. I wonder if we can remove the trace ID column and use the space to show the latency instead? Someone can already see the trace ID in the right hand side, and I'm not sure if there is another use case for showing it in the list..

<img width="1698" alt="Screenshot 2024-09-07 at 5 19 52 PM" src="https://github.com/user-attachments/assets/759918f7-32fa-40ce-b255-f148adc16a96">

**Comment by ymtdzzz** [comment]
I agree. There are some o11y products that show the trace ID in their trace or span list view (e.g. Splunk, Grafana Tempo), but when it comes to TUI, we should carefully consider which column is shown in the limited view width. As you say, we can see it and I think there is no reason to have it as a column in the list for now.

So I'd like to replace the trace ID with the span latency.

I'll consider how to keep the Trace ID column if requested in the future.
