### ISSUE TITLE
refresh span name when trace completes in traces list

### ISSUE THREAD

**Issue by codefromthecrypt** [ymtdzzz/otel-tui#161]
Right now, the trace list has the first span name to complete, not the first span name to start (root trace) in the list. I can't seem to have this refresh to see the much better name.

Example, when the trace is complete, I want to see "user" not "POST" for the last span, or be able to hit '/' and have it fix the list.

![Screenshot 2024-09-18 at 4 33 17 PM](https://github.com/user-attachments/assets/1a6aa0be-73b0-4cc5-b45f-55f0a583ee80)
![Screenshot 2024-09-18 at 4 33 30 PM](https://github.com/user-attachments/assets/f0430a1b-7539-4102-9a47-37f3854831af)

**Comment by ymtdzzz** [comment]
Certainly, the spans shown in the list are the service root spans "at the time of arrival at otel-tui".
Real-time updating would be implemented by modifying [`AddSpan()`](https://github.com/ymtdzzz/otel-tui/blob/8847baecec5f8f73471d1044d13b27d578963e97/tuiexporter/internal/telemetry/store.go#L264) to check if the received span is a parent of the currently stored service root span and swap them if necessary.

I'd like to work on this issue after closing https://github.com/ymtdzzz/otel-tui/issues/18 :)

Thanks for the suggestion as always!

**Comment by ymtdzzz** [comment]
I'm planning to work on this issue next week (after Kaigi on Rails 2024).

**Comment by ymtdzzz** [comment]
@codefromthecrypt , I think #172 solve this issue, could you check in that branch if you have time?

**Comment by ymtdzzz** [comment]
for now, I think #172 solves this issue.
@codefromthecrypt If you find any problems, please let me know :)

**Comment by codefromthecrypt** [comment]
yay! will do
