### ISSUE TITLE
refresh the images in the README

### ISSUE THREAD

**Issue by codefromthecrypt** [ymtdzzz/otel-tui#163]
I think some things have changed!

**Comment by ymtdzzz** [comment]
Yes, I'll update them later. And I'm thinking of making a script to take the screenshot automatically.

**Comment by ymtdzzz** [comment]
Maybe we can use [vhs](https://github.com/charmbracelet/vhs) . And adding JSON file receiver is also useful to receive the test data.

**Comment by ymtdzzz** [comment]
I close this issue because it's resolved in #173 .
Now, we can update images by executing a single make command :)

**Comment by codefromthecrypt** [comment]
good job!
