### ISSUE TITLE
when pressing enter on a very large span attribute, expand it

### ISSUE THREAD

**Issue by codefromthecrypt** [ymtdzzz/otel-tui#164]
Some people put large data in span attributes, so you won't be able to see it even if you change the width. It would be nice to be able to press enter and see the entire attribute value in this case. That, or something similar

<img width="1704" alt="Screenshot 2024-09-22 at 7 38 39 PM" src="https://github.com/user-attachments/assets/a9f4f18c-438b-464a-9f31-d9f777af4b75">

**Comment by ymtdzzz** [comment]
We can simply show a modal or something when pressing enter. This could be a solution of https://github.com/ymtdzzz/otel-tui/issues/38#issuecomment-2204768531 .
I'll take a look at.

**Comment by ymtdzzz** [comment]
Current progress ( never mind about the brightness of my terminal 😅 )
This modal is shown when pressing `Enter`. To close it, we can simply press `Enter` again or change the selection.

![image](https://github.com/user-attachments/assets/80fd79de-7cbb-42c1-ab09-763162e76c0a)
