### ISSUE TITLE
clear trace details on ctrl+l

### ISSUE THREAD

**Issue by codefromthecrypt** [ymtdzzz/otel-tui#186]
When you do ctrl+l it clears the list, but leaves stale details on the right-hand pane

<img width="985" alt="Screenshot 2024-12-19 at 10 30 21 AM" src="https://github.com/user-attachments/assets/508f3d47-cdba-4596-a16b-aa54d1337d42" />

**Comment by ymtdzzz** [comment]
This issue is solved in #187 :)
