### ISSUE TITLE
Text wrapping on Trace and Log info tree

### ISSUE THREAD

**Issue by ymtdzzz** [ymtdzzz/otel-tui#38]
![Image](https://github.com/ymtdzzz/otel-tui/assets/44557218/249ff3aa-4a2b-4b84-a8f2-0728d8f4cb14)

**Comment by ymtdzzz** [comment]
https://github.com/rivo/tview/issues/707#issuecomment-1099515709

There seems to be no way to support this feature at the moment. One of the simple solution is placing TextView in the bottom of the TreeView to display full string like Log view.

**Comment by codefromthecrypt** [comment]
Is it related or a different issue that I don't know how to scroll down the Details page by keystroke

<img width="2243" alt="Screenshot 2024-08-01 at 5 05 13 PM" src="https://github.com/user-attachments/assets/6804639a-49bf-47d4-ab78-8d6c4513197b">

**Comment by codefromthecrypt** [comment]
nevermind me. It was intuitive after all (d)

**Comment by ymtdzzz** [comment]
For now, I'd like to work on #131 instead of this issue.

**Comment by ymtdzzz** [comment]
#174 is also the solution for this issue!
